server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BJP-Learning-Space/multi-tenancy-config
          search-paths: /**
          default-label: main
